//// Generated by Selenium IDE
//package com.sakilaDB.TSI.matthew.barker.demoTest;
//
//import io.github.bonigarcia.wdm.WebDriverManager;
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.JavascriptExecutor;
//import java.util.*;
//import java.util.concurrent.TimeUnit;
//
//public class AddUpdateDeleteReviewTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  @Before
//  public void setUp() {
//    WebDriverManager.chromedriver().setup();
//    driver = new ChromeDriver();
//    js = (JavascriptExecutor) driver;
//    vars = new HashMap<String, Object>();
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void addUpdateDeleteReview() {
//    driver.get("http://18.234.64.191:3000/");
//    driver.manage().window().setSize(new Dimension(1539, 1188));
//    driver.findElement(By.cssSelector(".SearchBar > input")).click();
//    driver.findElement(By.cssSelector(".SearchBar > input")).sendKeys("Rush Hour");
//    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
//    driver.findElement(By.xpath("//input[@value=\'\']")).click();
//    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
//    driver.findElement(By.xpath("//input[@value=\'1001\']")).sendKeys("1001");
//    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
//    driver.findElement(By.xpath("//input[@value=\'\']")).click();
//    driver.findElement(By.xpath("//input[@value=\'Test\']")).sendKeys("Test");
//    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
//    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
//    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
//    driver.findElement(By.cssSelector(".SearchBar > input")).click();
//    driver.findElement(By.cssSelector(".SearchBar > input")).sendKeys("rush hour");
//    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
//    driver.findElement(By.xpath("(//input[@value=\'\'])[3]")).click();
//    driver.findElement(By.xpath("//input[@value=\'17\']")).sendKeys("17");
//    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
//    driver.findElement(By.xpath("(//input[@value=\'\'])[3]")).click();
//    driver.findElement(By.xpath("//input[@value=\'Test add worked\']")).sendKeys("Test add worked");
//    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
//    driver.findElement(By.xpath("(//button[@type=\'submit\'])[2]")).click();
//    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
//    driver.findElement(By.cssSelector("input")).click();
//    driver.findElement(By.cssSelector(".SearchBar > input")).sendKeys("rush hour");
//    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
//    driver.findElement(By.xpath("//p[@id=\'reviewMap\']/div[3]/form/input")).click();
//    driver.findElement(By.xpath("//p[@id=\'reviewMap\']/div[3]/form/input")).sendKeys("17");
//    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
//    driver.findElement(By.xpath("(//button[@type=\'submit\'])[3]")).click();
//  }
//}
